// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001123913_22")]
    partial class _22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chiếu sáng thông minh",
                            Description = "Bóng đèn thông minh, dây LED, đèn cảm ứng"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "An ninh & Camera",
                            Description = "Camera giám sát trong/ngoài trời, chuông cửa màn hình"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Khóa cửa thông minh",
                            Description = "Khóa vân tay, khóa nhận diện khuôn mặt, thẻ từ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cảm biến thông minh",
                            Description = "Cảm biến chuyển động, nhiệt độ, cửa, khói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Công tắc & Ổ cắm",
                            Description = "Công tắc cảm ứng WiFi/Zigbee, ổ cắm điều khiển từ xa"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Loa & Trợ lý ảo",
                            Description = "Loa Google Nest, Amazon Echo, Apple HomePod"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Nhà bếp thông minh",
                            Description = "Nồi chiên không dầu tự động, máy pha cà phê thông minh"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Robot hút bụi & Lau nhà",
                            Description = "Robot dọn dẹp tự động, máy hút bụi cầm tay"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Xử lý không khí",
                            Description = "Máy lọc không khí, máy tạo ẩm, máy hút ẩm thông minh"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Điều khiển trung tâm (Hub)",
                            Description = "Bộ điều khiển trung tâm Aqara, Tuya, Xiaomi"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Động cơ & Rèm cửa",
                            Description = "Động cơ rèm cuốn, rèm vải thông minh tự động"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Thiết bị vệ sinh thông minh",
                            Description = "Nắp bồn cầu tự động, máy sấy tay, gương thông minh"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Chăm sóc sức khỏe",
                            Description = "Cân sức khỏe thông minh, máy đo huyết áp kết nối app"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Sân vườn tự động",
                            Description = "Van tưới cây tự động, máy cắt cỏ robot"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Phụ kiện Smart Home",
                            Description = "Pin, dây cáp, remote, bộ chuyển đổi tín hiệu"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Quận 3, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Quận 5, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 100
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 2300
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Quận Gò Vấp, TP.HCM",
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Quận Tân Bình, TP.HCM",
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909876543",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Quận 7, TP.HCM",
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0981234567",
                            RewardPoints = 4500
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Quận 6, TP.HCM",
                            CustomerName = "Nguyễn Thị K",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "TP. Thủ Đức, TP.HCM",
                            CustomerName = "Trương Văn L",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0915678901",
                            RewardPoints = 1800
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Quận 12, TP.HCM",
                            CustomerName = "Phan Thị M",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0986789012",
                            RewardPoints = 700
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Quận Tân Phú, TP.HCM",
                            CustomerName = "Lý Văn N",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0907890123",
                            RewardPoints = 5000
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Quận Bình Tân, TP.HCM",
                            CustomerName = "Huỳnh Thị P",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918901234",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Huyện Bình Chánh, TP.HCM",
                            CustomerName = "Mai Văn Q",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989012345",
                            RewardPoints = 2600
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "SMH000001",
                            CategoryId = 1,
                            Price = 1290000m,
                            ProductName = "Bóng đèn thông minh Philips Hue Color",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "SMH000002",
                            CategoryId = 2,
                            Price = 550000m,
                            ProductName = "Camera WiFi xoay 360 Ezviz C6N",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "SMH000003",
                            CategoryId = 3,
                            Price = 4500000m,
                            ProductName = "Khóa cửa vân tay thông minh Xiaomi",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "SMH000004",
                            CategoryId = 4,
                            Price = 350000m,
                            ProductName = "Cảm biến chuyển động gắn tường Aqara",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "SMH000005",
                            CategoryId = 5,
                            Price = 150000m,
                            ProductName = "Ổ cắm điện WiFi đo công suất Tuya",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "SMH000006",
                            CategoryId = 6,
                            Price = 690000m,
                            ProductName = "Loa trợ lý ảo Google Nest Mini",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "SMH000007",
                            CategoryId = 7,
                            Price = 1490000m,
                            ProductName = "Nồi chiên không dầu Xiaomi Smart Air Fryer",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "SMH000008",
                            CategoryId = 8,
                            Price = 24990000m,
                            ProductName = "Robot hút bụi Roborock S8 Pro Ultra",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "SMH000009",
                            CategoryId = 9,
                            Price = 3290000m,
                            ProductName = "Máy lọc không khí Xiaomi Mi Air Purifier 4",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "SMH000010",
                            CategoryId = 10,
                            Price = 1190000m,
                            ProductName = "Bộ điều khiển trung tâm Aqara Hub M2",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "SMH000011",
                            CategoryId = 11,
                            Price = 1250000m,
                            ProductName = "Động cơ rèm cuốn tự động Tuya WiFi",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "SMH000012",
                            CategoryId = 12,
                            Price = 8500000m,
                            ProductName = "Nắp bồn cầu sưởi ấm thông minh TOTO",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "SMH000013",
                            CategoryId = 13,
                            Price = 390000m,
                            ProductName = "Cân sức khỏe thông minh Xiaomi Body Composition",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "SMH000014",
                            CategoryId = 14,
                            Price = 850000m,
                            ProductName = "Van nước tưới cây tự động WiFi",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "SMH000015",
                            CategoryId = 15,
                            Price = 180000m,
                            ProductName = "Bộ Hub hồng ngoại điều khiển TV/Điều hòa",
                            StockQuantity = 150
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
