// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001122153_SeedProductData")]
    partial class SeedProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Gạo & Ngũ cốc",
                            Description = "Gạo, yến mạch, ngũ cốc"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ hộp",
                            Description = "Cá hộp, thịt hộp, rau củ đóng hộp"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Thịt đông lạnh, hải sản, thực phẩm chế biến"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Rau củ quả",
                            Description = "Rau xanh, củ và trái cây"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Thịt & Hải sản",
                            Description = "Thịt heo, thịt bò, gà và hải sản"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Khăn giấy, túi rác, dụng cụ nhà bếp"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Hóa mỹ phẩm",
                            Description = "Dầu gội, sữa tắm, xà phòng"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Kem đánh răng, bàn chải, nước súc miệng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đồ uống dinh dưỡng",
                            Description = "Nước ép, sữa hạt, nước bổ sung vitamin"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Thực phẩm khô",
                            Description = "Mộc nhĩ, nấm khô, đậu và thực phẩm khô"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Quận 3, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Quận 5, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 230
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Quận Gò Vấp, TP.HCM",
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0987654321",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Quận Tân Bình, TP.HCM",
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909876543",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Quận 7, TP.HCM",
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0981234567",
                            RewardPoints = 450
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Quận 6, TP.HCM",
                            CustomerName = "Nguyễn Thị K",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "TP. Thủ Đức, TP.HCM",
                            CustomerName = "Trương Văn L",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915678901",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Quận 12, TP.HCM",
                            CustomerName = "Phan Thị M",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0986789012",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Quận Tân Phú, TP.HCM",
                            CustomerName = "Lý Văn N",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907890123",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Quận Bình Tân, TP.HCM",
                            CustomerName = "Huỳnh Thị P",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918901234",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Huyện Bình Chánh, TP.HCM",
                            CustomerName = "Mai Văn Q",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989012345",
                            RewardPoints = 260
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893123450001",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Bánh Oreo vị socola",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893123450002",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước ngọt Coca Cola 330ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893123450003",
                            CategoryId = 3,
                            Price = 35000m,
                            ProductName = "Sữa tươi Vinamilk 1L",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893123450004",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893123450005",
                            CategoryId = 5,
                            Price = 28000m,
                            ProductName = "Nước mắm Nam Ngư 500ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893123450006",
                            CategoryId = 6,
                            Price = 145000m,
                            ProductName = "Gạo ST25 5kg",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893123450007",
                            CategoryId = 7,
                            Price = 32000m,
                            ProductName = "Cá ngừ đóng hộp",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893123450008",
                            CategoryId = 8,
                            Price = 45000m,
                            ProductName = "Xúc xích tiệt trùng",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893123450009",
                            CategoryId = 9,
                            Price = 75000m,
                            ProductName = "Táo Mỹ",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893123450010",
                            CategoryId = 10,
                            Price = 180000m,
                            ProductName = "Thịt bò thăn",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893123450011",
                            CategoryId = 11,
                            Price = 25000m,
                            ProductName = "Khăn giấy Pulppy",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893123450012",
                            CategoryId = 12,
                            Price = 85000m,
                            ProductName = "Dầu gội Sunsilk 650g",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893123450013",
                            CategoryId = 13,
                            Price = 38000m,
                            ProductName = "Kem đánh răng P/S 180g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893123450014",
                            CategoryId = 14,
                            Price = 18000m,
                            ProductName = "Nước ép cam Twister",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893123450015",
                            CategoryId = 15,
                            Price = 42000m,
                            ProductName = "Nấm hương khô 100g",
                            StockQuantity = 45
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
