// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008073634_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Xiaomi",
                            Description = "Hệ sinh thái nhà thông minh Xiaomi Mijia"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Tuya Smart",
                            Description = "Nền tảng IoT Tuya toàn cầu"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Philips",
                            Description = "Chuyên các thiết bị chiếu sáng thông minh Philips Hue"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Aqara",
                            Description = "Thương hiệu cao cấp thuộc hệ sinh thái Apple HomeKit"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Amazon",
                            Description = "Thiết bị loa và màn hình thông minh Alexa"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chiếu sáng thông minh",
                            Description = "Bóng đèn thông minh, dây LED, đèn cảm ứng"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "An ninh & Camera",
                            Description = "Camera giám sát trong/ngoài trời, chuông cửa màn hình"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Khóa cửa thông minh",
                            Description = "Khóa vân tay, khóa nhận diện khuôn mặt, thẻ từ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cảm biến thông minh",
                            Description = "Cảm biến chuyển động, nhiệt độ, cửa, khói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Công tắc & Ổ cắm",
                            Description = "Công tắc cảm ứng WiFi/Zigbee, ổ cắm điều khiển từ xa"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Loa & Trợ lý ảo",
                            Description = "Loa Google Nest, Amazon Echo, Apple HomePod"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Nhà bếp thông minh",
                            Description = "Nồi chiên không dầu tự động, máy pha cà phê thông minh"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Robot hút bụi & Lau nhà",
                            Description = "Robot dọn dẹp tự động, máy hút bụi cầm tay"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Xử lý không khí",
                            Description = "Máy lọc không khí, máy tạo ẩm, máy hút ẩm thông minh"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Điều khiển trung tâm (Hub)",
                            Description = "Bộ điều khiển trung tâm Aqara, Tuya, Xiaomi"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Động cơ & Rèm cửa",
                            Description = "Động cơ rèm cuốn, rèm vải thông minh tự động"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Thiết bị vệ sinh thông minh",
                            Description = "Nắp bồn cầu tự động, máy sấy tay, gương thông minh"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Chăm sóc sức khỏe",
                            Description = "Cân sức khỏe thông minh, máy đo huyết áp kết nối app"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Sân vườn tự động",
                            Description = "Van tưới cây tự động, máy cắt cỏ robot"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Phụ kiện Smart Home",
                            Description = "Pin, dây cáp, remote, bộ chuyển đổi tín hiệu"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "25 Nguyễn Huệ, Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "118 Võ Văn Tần, Quận 3, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "72 Nguyễn Trãi, Quận 5, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 100
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "156 Thành Thái, Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 2300
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "43 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Phạm Văn Đồng, Quận Gò Vấp, TP.HCM",
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "215 Cộng Hòa, Quận Tân Bình, TP.HCM",
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909876543",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "36 Phan Đình Phùng, Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "102 Nguyễn Thị Thập, Quận 7, TP.HCM",
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0981234567",
                            RewardPoints = 4500
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "68 Hậu Giang, Quận 6, TP.HCM",
                            CustomerName = "Nguyễn Thị K",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "145 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
                            CustomerName = "Trương Văn L",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0915678901",
                            RewardPoints = 1800
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "234 Lê Văn Khương, Quận 12, TP.HCM",
                            CustomerName = "Phan Thị M",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0986789012",
                            RewardPoints = 700
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "57 Lũy Bán Bích, Quận Tân Phú, TP.HCM",
                            CustomerName = "Lý Văn N",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0907890123",
                            RewardPoints = 5000
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "321 Tỉnh Lộ 10, Quận Bình Tân, TP.HCM",
                            CustomerName = "Huỳnh Thị P",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918901234",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "78 Nguyễn Hữu Trí, Huyện Bình Chánh, TP.HCM",
                            CustomerName = "Mai Văn Q",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989012345",
                            RewardPoints = 2600
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 10, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "25 Nguyễn Huệ, Quận 1, TP.HCM",
                            Status = "Đã giao hàng",
                            TotalAmount = 2950000m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 10, 5, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "118 Võ Văn Tần, Quận 3, TP.HCM",
                            Status = "Đang xử lý",
                            TotalAmount = 2300000m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 6,
                            OrderDate = new DateTime(2023, 10, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "89 Phạm Văn Đồng, Quận Gò Vấp, TP.HCM",
                            Status = "Đã giao hàng",
                            TotalAmount = 14100000m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 9,
                            OrderDate = new DateTime(2023, 10, 12, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "102 Nguyễn Thị Thập, Quận 7, TP.HCM",
                            Status = "Đã hủy",
                            TotalAmount = 650000m
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 13,
                            OrderDate = new DateTime(2023, 10, 15, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "57 Lũy Bán Bích, Quận Tân Phú, TP.HCM",
                            Status = "Đang giao hàng",
                            TotalAmount = 4300000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 450000m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 2500000m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 1800000m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 2,
                            ProductId = 20,
                            Quantity = 2,
                            UnitPrice = 250000m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 3,
                            ProductId = 23,
                            Quantity = 1,
                            UnitPrice = 12000000m
                        },
                        new
                        {
                            OrderDetailId = 6,
                            OrderId = 3,
                            ProductId = 21,
                            Quantity = 1,
                            UnitPrice = 2100000m
                        },
                        new
                        {
                            OrderDetailId = 7,
                            OrderId = 4,
                            ProductId = 25,
                            Quantity = 1,
                            UnitPrice = 650000m
                        },
                        new
                        {
                            OrderDetailId = 8,
                            OrderId = 5,
                            ProductId = 26,
                            Quantity = 1,
                            UnitPrice = 1850000m
                        },
                        new
                        {
                            OrderDetailId = 9,
                            OrderId = 5,
                            ProductId = 27,
                            Quantity = 1,
                            UnitPrice = 2200000m
                        },
                        new
                        {
                            OrderDetailId = 10,
                            OrderId = 5,
                            ProductId = 20,
                            Quantity = 1,
                            UnitPrice = 250000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 16,
                            Barcode = "SMH000016",
                            BrandId = 3,
                            CategoryId = 1,
                            Price = 450000m,
                            ProductName = "Dây LED thông minh RGB trang trí phòng",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "SMH000017",
                            BrandId = 5,
                            CategoryId = 2,
                            Price = 2500000m,
                            ProductName = "Chuông cửa màn hình thông minh Ring",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "SMH000018",
                            BrandId = 2,
                            CategoryId = 3,
                            Price = 1800000m,
                            ProductName = "Khóa cửa thẻ từ khách sạn Tuya",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "SMH000019",
                            BrandId = 1,
                            CategoryId = 4,
                            Price = 400000m,
                            ProductName = "Cảm biến báo khói báo cháy thông minh",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "SMH000020",
                            BrandId = 2,
                            CategoryId = 5,
                            Price = 250000m,
                            ProductName = "Công tắc cảm ứng âm tường mặt kính 3 nút",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "SMH000021",
                            BrandId = 5,
                            CategoryId = 6,
                            Price = 2100000m,
                            ProductName = "Màn hình thông minh Amazon Echo Show 8",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "SMH000022",
                            BrandId = 1,
                            CategoryId = 7,
                            Price = 3500000m,
                            ProductName = "Máy pha cà phê thông minh kết nối WiFi",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "SMH000023",
                            BrandId = 1,
                            CategoryId = 8,
                            Price = 12000000m,
                            ProductName = "Máy hút bụi cầm tay không dây Dyson",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "SMH000024",
                            BrandId = 1,
                            CategoryId = 9,
                            Price = 550000m,
                            ProductName = "Máy tạo độ ẩm thông minh Deerma",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "SMH000025",
                            BrandId = 4,
                            CategoryId = 10,
                            Price = 650000m,
                            ProductName = "Bộ điều khiển trung tâm Zigbee 3.0",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "SMH000026",
                            BrandId = 1,
                            CategoryId = 11,
                            Price = 1850000m,
                            ProductName = "Động cơ kéo rèm vải thông minh Xiaomi",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "SMH000027",
                            BrandId = 2,
                            CategoryId = 12,
                            Price = 2200000m,
                            ProductName = "Gương thông minh tích hợp đèn LED phòng tắm",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "SMH000028",
                            BrandId = 1,
                            CategoryId = 13,
                            Price = 1450000m,
                            ProductName = "Máy đo huyết áp bắp tay Bluetooth Omron",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "SMH000029",
                            BrandId = 2,
                            CategoryId = 14,
                            Price = 18000000m,
                            ProductName = "Robot cắt cỏ tự động ngoài trời",
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "SMH000030",
                            BrandId = 4,
                            CategoryId = 15,
                            Price = 120000m,
                            ProductName = "Cảm biến nhiệt độ và độ ẩm phòng",
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
